webtalk_init -webtalk_dir /net/s/mgeraud001/enseirb/EN224-Test-et-verification-master/2_Hardware/Etape_3/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_PGCD_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 11 17:12:52 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "202409907_1777491908_210660663_640" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "842d8e3c7d005c50b87da12074e912e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "07a9fe2a1959459da5ff7aa509eeb71b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.8.2003 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3797.790 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2600036389 -regid "202409907_1777491908_210660663_640" -xml /net/s/mgeraud001/enseirb/EN224-Test-et-verification-master/2_Hardware/Etape_3/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_PGCD_behav/webtalk/usage_statistics_ext_xsim.xml -html /net/s/mgeraud001/enseirb/EN224-Test-et-verification-master/2_Hardware/Etape_3/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_PGCD_behav/webtalk/usage_statistics_ext_xsim.html -wdm /net/s/mgeraud001/enseirb/EN224-Test-et-verification-master/2_Hardware/Etape_3/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_top_level_PGCD_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
